### ISSUE TITLE
Checking Deallocation on ViewController 'owned' by UITabBarController

### ISSUE THREAD

**Issue by sheinix** [fastred/DeallocationChecker#9]
Does checking for deallocation in viewDidDissapear() of a ViewController hold by a UITabBarController make sense?
If UIKit handles when to deinit VC's on a UITabBarcontroller, could be the case that asserting if self is nil after disappearing not always is right?

**Comment by fastred** [comment]
That's correct. `UITabBarController` keeps a strong reference to all view controllers, even when they're currently not displayed on screen. So, there's no need to confirm deallocation of view controllers in this case because they won't be deallocated until the tab bar controller is deallocated itself.

**Comment by sheinix** [comment]
Thanks!, I thought that, but wasn't sure.  Could be any sort of checking before the asserting if the VC is owned by a UITabBarController?

**Comment by fastred** [comment]
@sheinix I think it should have been fixed in 3.0. I added an explicit check for this case.
